-- ==============================================================================
-- Mazdoor Mitra - Production Supabase Cloud Schema
-- Project Reference: eeocbfsgsqpymnnnzcmk
-- https://eeocbfsgsqpymnnnzcmk.supabase.co
--
-- INSTRUCTIONS:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard/project/eeocbfsgsqpymnnnzcmk
-- 2. Go to "SQL Editor" in the left sidebar
-- 3. Click "New Query", paste this entire script, and click "Run"
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. TABLE DEFINITIONS
-- ==============================================================================

-- 2.1 JOBS TABLE (Active Job Openings Across India)
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    trade TEXT NOT NULL,
    employer TEXT NOT NULL,
    employer_phone TEXT DEFAULT '9876543210',
    phone TEXT DEFAULT '9876543210',
    wage INTEGER NOT NULL CHECK (wage >= 300),
    workers_needed INTEGER DEFAULT 1,
    hours TEXT DEFAULT '8 hours',
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    city TEXT NOT NULL,
    description TEXT,
    posted_date TEXT DEFAULT CURRENT_DATE::text,
    is_scam BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.2 WORKERS DIRECTORY TABLE
CREATE TABLE IF NOT EXISTS public.workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    trade TEXT NOT NULL,
    wage INTEGER NOT NULL CHECK (wage >= 300),
    experience INTEGER DEFAULT 1,
    status TEXT DEFAULT 'Available',
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    city TEXT NOT NULL,
    verified BOOLEAN DEFAULT true,
    photo_skill_verified BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.3 APPLICATIONS TABLE (Job Applications from Workers)
CREATE TABLE IF NOT EXISTS public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT,
    job_title TEXT,
    worker_name TEXT NOT NULL,
    worker_phone TEXT NOT NULL,
    worker_trade TEXT NOT NULL,
    status TEXT DEFAULT 'Submitted',
    applied_date TEXT DEFAULT CURRENT_DATE::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.4 ATTENDANCE LOGS TABLE (Facial / Geotagged Check-ins)
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name TEXT NOT NULL,
    date TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    type TEXT DEFAULT 'Check-In',
    location TEXT,
    verified BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.5 INCIDENTS / SAFETY INJURY LOGS TABLE
CREATE TABLE IF NOT EXISTS public.incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name TEXT NOT NULL,
    incident_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    contractor_phone TEXT,
    location TEXT NOT NULL,
    description TEXT,
    timestamp TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

-- Allow public read & write access for PWA client (Anon Key)
CREATE POLICY "Allow public read access on jobs" ON public.jobs FOR SELECT USING (true);
CREATE POLICY "Allow public insert on jobs" ON public.jobs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on jobs" ON public.jobs FOR UPDATE USING (true);

CREATE POLICY "Allow public read access on workers" ON public.workers FOR SELECT USING (true);
CREATE POLICY "Allow public insert on workers" ON public.workers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on workers" ON public.workers FOR UPDATE USING (true);

CREATE POLICY "Allow public read access on applications" ON public.applications FOR SELECT USING (true);
CREATE POLICY "Allow public insert on applications" ON public.applications FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on attendance" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Allow public insert on attendance" ON public.attendance FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read access on incidents" ON public.incidents FOR SELECT USING (true);
CREATE POLICY "Allow public insert on incidents" ON public.incidents FOR INSERT WITH CHECK (true);

-- Enable Realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE public.jobs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.workers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.applications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance;

-- ==============================================================================
-- 4. SEED INITIAL JOBS DATA (12 Verified Real Jobs Across India)
-- ==============================================================================
INSERT INTO public.jobs (title, trade, employer, employer_phone, phone, wage, workers_needed, hours, state, district, city, description, posted_date, is_scam)
VALUES
('Civil Construction Mason (Mistri)', 'Masonry / Rajmistri', 'L&T Metro Rail Project', '011-2334000', '011-2334000', 950, 4, '8 hours', 'Delhi', 'South Delhi', 'Okhla Phase 3', 'Brickwork, structural AAC block alignment, and beam plastering for elevated corridor station building. Safety helmet and boots provided at gate.', '2026-09-28', false),
('Commercial Interior Wall Painter', 'Painting & Finishing', 'Godrej Properties Luxury Towers', '040-2345000', '040-2345000', 850, 3, '8 hours', 'Telangana', 'Hyderabad', 'Gachibowli', 'Putty smoothing, primer coat, and double roller emulsion application on 2BHK interior ceilings and partition walls. Immediate daily payout.', '2026-09-28', false),
('Three-Phase Industrial Conduit Electrician', 'Electrical & Wiring', 'Tata BlueScope Industrial Sheds', '020-2740000', '020-2740000', 1000, 2, '8 hours', 'Maharashtra', 'Pune', 'Bhosari MIDC', 'Rigid PVC/GI cable tray laying, three-phase distribution box termination, and continuity testing for manufacturing warehouse. Certified Wireman preferred.', '2026-09-27', false),
('Sanitary Drainage & CPVC Pipeline Fitter', 'Plumbing & Sanitation', 'Prestige Tech Cloud Park', '080-2558000', '080-2558000', 900, 3, '8 hours', 'Karnataka', 'Bengaluru Urban', 'Electronic City', 'Vertical shaft drainage stack jointing, underground sewer line slope alignment, and hydro-testing of pressure lines in commercial block.', '2026-09-28', false),
('Architectural Flush Door & Modular Carpenter', 'Carpentry & Woodwork', 'Adani Shantigram Township', '079-2656000', '079-2656000', 950, 5, '8 hours', 'Gujarat', 'Ahmedabad', 'Vaishno Devi Circle', 'Pre-hung door frame leveling, lock mortising, and modular laminate wardrobe carcass installation for luxury high-rise apartments.', '2026-09-27', false),
('HVAC Ducting & Heavy Plate MIG Welder', 'Welding & Fabrication', 'KEC International Heavy Fab Yard', '033-2287000', '033-2287000', 1050, 2, '8 hours', 'West Bengal', 'Kolkata', 'Taratala Industrial Area', 'CO2 Shielded MIG welding of heavy structural box girders and ventilation ducts. Must pass horizontal fillet weld visual inspection.', '2026-09-26', false),
('Heavy-Duty Bar Bending & Mat Tier (Rebar)', 'Bar Bending / Steel Fixing', 'Dilip Buildcon Highway Interchange', '0141-2740000', '0141-2740000', 850, 8, '8 hours', 'Rajasthan', 'Jaipur', 'Mansarovar', 'Cutting and manual lever-bending of 16mm/25mm Fe-550D TMT bars, tying reinforcement cage mats for highway bridge pier foundations.', '2026-09-28', false),
('Heavy Earthmoving Excavator / JCB Operator', 'Heavy Equipment Operation', 'Megha Engineering & Infra (MEIL)', '0866-2470000', '0866-2470000', 1200, 1, '8 hours', 'Andhra Pradesh', 'Krishna', 'Vijayawada', 'Operating 20-ton tracked excavator for canal embankment trenching and backfilling. Valid Heavy Commercial driving license mandatory.', '2026-09-27', false),
('High-Rise Cuplock Scaffolding & Catch-Net Rigger', 'Scaffolding & Rigging', 'Shapoorji Pallonji Engineering', '0124-4552000', '0124-4552000', 950, 5, '8 hours', 'Haryana', 'Gurugram', 'Cyber City', 'Erecting external cantilevered cuplock staging, toe-boards, and safety catch nets up to 14th floor level. Full safety compliance required.', '2026-09-28', false),
('Underground Stormwater Drainage & Chamber Mason', 'Civil Masonry & Pipe Laying', 'Afcons Infrastructure Ltd', '044-26882000', '044-26882000', 900, 6, '8 hours', 'Tamil Nadu', 'Chennai', 'Ambattur', 'Aligning reinforced concrete NP3 pipes, joint grouting, and manhole brick chamber masonry. PPE and hydration provisions on site.', '2026-09-27', false),
('Structural Steel Shielded Metal Arc Welder (SMAW)', 'Structural Arc Welding', 'Bharat Heavy Electricals Project Site', '0542-2582000', '0542-2582000', 1100, 4, '8 hours', 'Uttar Pradesh', 'Varanasi', 'Ramnagar', 'Multi-pass fillet and groove welding of structural MS I-beams and gusset plates. Auto-darkening welding helmet provided.', '2026-09-26', false),
('National Highway Elevated Flyover Formwork Carpenter', 'Formwork Carpentry', 'National Highways Authority Contractors', '0612-2592000', '0612-2592000', 950, 6, '8 hours', 'Bihar', 'Patna', 'Danapur', 'Steel-faced plywood formwork erection, prop alignment, and releasing oil application for PSC box girders. Lunch break and fresh drinking water on site.', '2026-09-28', false)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- 5. SEED INITIAL WORKERS DATA
-- ==============================================================================
INSERT INTO public.workers (name, phone, trade, wage, experience, status, state, district, city, verified, photo_skill_verified)
VALUES
('Sunil Sharma', '9848011223', 'Masonry / Rajmistri', 950, 8, 'Available', 'Telangana', 'Hyderabad', 'Gachibowli', true, true),
('Pradeep Patil', '9822014455', 'Painting', 900, 6, 'Available', 'Maharashtra', 'Pune', 'Kothrud', true, true),
('Balasubramanian S.', '9840015566', 'Electrician', 950, 6, 'Available', 'Tamil Nadu', 'Chennai', 'Ambattur', true, true),
('Rajesh Patidar', '9879016677', 'Carpentry', 900, 7, 'Available', 'Gujarat', 'Ahmedabad', 'Sanand', true, true),
('Dilip Mondal', '9831017788', 'Plumbing', 850, 5, 'Available', 'West Bengal', 'Kolkata', 'Salt Lake', true, true)
ON CONFLICT DO NOTHING;
