-- ==============================================================================
-- Mazdoor Mitra - Production Supabase Cloud Schema & Migration
-- Project Reference: eeocbfsgsqpymnnnzcmk
-- https://eeocbfsgsqpymnnnzcmk.supabase.co
--
-- INSTRUCTIONS:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard/project/eeocbfsgsqpymnnnzcmk
-- 2. Go to "SQL Editor" in the left sidebar
-- 3. Click "New Query", paste this entire script, and click "Run"
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. IDEMPOTENT SCHEMA MIGRATION (Safe for Existing Live Databases)
-- ==============================================================================
-- 2.1 MIGRATIONS FOR public.jobs (Employer Ecosystem Upgrades)
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS employer_id TEXT DEFAULT 'contractor-self';
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS skills_required TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS workers_count INTEGER DEFAULT 1;
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS wage_per_day INTEGER;
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS site_address TEXT DEFAULT '';
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS landmark TEXT DEFAULT '';
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS duration TEXT DEFAULT '1-2 Weeks';
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS contact_number TEXT DEFAULT '';
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'open';

-- 2.2 MIGRATIONS FOR public.workers (Dual Role Worker/Employer Accounts)
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'worker';
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS business_category TEXT;
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS gstin TEXT;

-- 2.3 MIGRATIONS FOR public.applications
ALTER TABLE IF EXISTS public.applications ADD COLUMN IF NOT EXISTS employer_phone TEXT;
ALTER TABLE IF EXISTS public.applications ADD COLUMN IF NOT EXISTS employer_id TEXT;

-- 2.4 MIGRATIONS FOR LIVE GEOLOCATION & REAL-TIME ADDRESS SYNC
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS current_area TEXT;
ALTER TABLE IF EXISTS public.workers ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.jobs ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

-- 2.5 MIGRATIONS FOR ATTENDANCE & SELFIE CHECK-IN
ALTER TABLE IF EXISTS public.attendance ADD COLUMN IF NOT EXISTS worker_id TEXT;
ALTER TABLE IF EXISTS public.attendance ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.attendance ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE IF EXISTS public.attendance ADD COLUMN IF NOT EXISTS location_name TEXT;
ALTER TABLE IF EXISTS public.attendance ADD COLUMN IF NOT EXISTS selfie_url TEXT;
ALTER TABLE IF EXISTS public.attendance ADD COLUMN IF NOT EXISTS checkin_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE IF EXISTS public.attendance ADD COLUMN IF NOT EXISTS geofence_status TEXT DEFAULT 'verified';

-- ==============================================================================
-- 3. FULL BASELINE TABLE DEFINITIONS (If Initializing from Scratch)
-- ==============================================================================

-- 3.1 JOBS TABLE (Active Job Postings from Employers & Contractors)
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    trade TEXT NOT NULL,
    employer TEXT NOT NULL,
    employer_id TEXT DEFAULT 'contractor-self',
    employer_phone TEXT DEFAULT '9876543210',
    phone TEXT DEFAULT '9876543210',
    contact_number TEXT DEFAULT '9876543210',
    wage INTEGER NOT NULL CHECK (wage >= 0),
    wage_per_day INTEGER DEFAULT 850,
    workers_needed INTEGER DEFAULT 1,
    workers_count INTEGER DEFAULT 1,
    hours TEXT DEFAULT '8 hours',
    duration TEXT DEFAULT '1-2 Weeks',
    site_address TEXT DEFAULT '',
    landmark TEXT DEFAULT '',
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    city TEXT NOT NULL,
    skills_required TEXT[] DEFAULT '{}',
    description TEXT,
    posted_date TEXT DEFAULT CURRENT_DATE::text,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled')),
    is_scam BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.2 WORKERS & EMPLOYERS DIRECTORY TABLE
CREATE TABLE IF NOT EXISTS public.workers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    trade TEXT NOT NULL,
    role TEXT DEFAULT 'worker' CHECK (role IN ('worker', 'employer')),
    company_name TEXT,
    business_category TEXT,
    gstin TEXT,
    wage INTEGER NOT NULL DEFAULT 0,
    experience INTEGER DEFAULT 1,
    status TEXT DEFAULT 'Available',
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    city TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    current_area TEXT,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    verified BOOLEAN DEFAULT true,
    photo_skill_verified BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.3 CANDIDATE APPLICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT,
    job_title TEXT,
    employer_id TEXT,
    employer_phone TEXT,
    worker_name TEXT NOT NULL,
    worker_phone TEXT NOT NULL,
    worker_trade TEXT NOT NULL,
    status TEXT DEFAULT 'Submitted' CHECK (status IN ('Submitted', 'Shortlisted', 'Hired', 'Rejected')),
    applied_date TEXT DEFAULT CURRENT_DATE::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.4 ATTENDANCE LOGS TABLE (Geotagged & Facial Check-ins)
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name TEXT NOT NULL,
    date TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    type TEXT DEFAULT 'Check-In',
    location TEXT,
    verified BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3.5 INCIDENTS / SAFETY REPORTING TABLE
CREATE TABLE IF NOT EXISTS public.incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_name TEXT NOT NULL,
    incident_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    contractor_phone TEXT,
    location TEXT NOT NULL,
    description TEXT,
    timestamp TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

-- 4.1 JOBS POLICIES (Read Active Jobs, Post Jobs, Update Own Jobs)
DROP POLICY IF EXISTS "Allow public read access on jobs" ON public.jobs;
CREATE POLICY "Allow public read access on jobs" ON public.jobs 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on jobs" ON public.jobs;
CREATE POLICY "Allow public insert on jobs" ON public.jobs 
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on jobs" ON public.jobs;
CREATE POLICY "Allow public update on jobs" ON public.jobs 
    FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete on jobs" ON public.jobs;
CREATE POLICY "Allow public delete on jobs" ON public.jobs 
    FOR DELETE USING (true);

-- 4.2 WORKERS & EMPLOYERS POLICIES
DROP POLICY IF EXISTS "Allow public read access on workers" ON public.workers;
CREATE POLICY "Allow public read access on workers" ON public.workers 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on workers" ON public.workers;
CREATE POLICY "Allow public insert on workers" ON public.workers 
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on workers" ON public.workers;
CREATE POLICY "Allow public update on workers" ON public.workers 
    FOR UPDATE USING (true);

-- 4.3 APPLICATIONS POLICIES (Apply & Manage Candidates)
DROP POLICY IF EXISTS "Allow public read access on applications" ON public.applications;
CREATE POLICY "Allow public read access on applications" ON public.applications 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on applications" ON public.applications;
CREATE POLICY "Allow public insert on applications" ON public.applications 
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on applications" ON public.applications;
CREATE POLICY "Allow public update on applications" ON public.applications 
    FOR UPDATE USING (true);

-- 4.4 ATTENDANCE POLICIES
DROP POLICY IF EXISTS "Allow public read access on attendance" ON public.attendance;
CREATE POLICY "Allow public read access on attendance" ON public.attendance 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on attendance" ON public.attendance;
CREATE POLICY "Allow public insert on attendance" ON public.attendance 
    FOR INSERT WITH CHECK (true);

-- 4.5 INCIDENTS POLICIES
DROP POLICY IF EXISTS "Allow public read access on incidents" ON public.incidents;
CREATE POLICY "Allow public read access on incidents" ON public.incidents 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on incidents" ON public.incidents;
CREATE POLICY "Allow public insert on incidents" ON public.incidents 
    FOR INSERT WITH CHECK (true);

-- ==============================================================================
-- 5. REALTIME REPLICATION SETUP
-- ==============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'jobs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.jobs;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'workers'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.workers;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'applications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.applications;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'attendance'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance;
  END IF;
END $$;

-- ==============================================================================
-- 6. SEED INITIAL JOBS DATA (12 Verified Real Jobs Across India)
-- ==============================================================================
INSERT INTO public.jobs (
    title, trade, employer, employer_id, employer_phone, phone, contact_number, 
    wage, wage_per_day, workers_needed, workers_count, hours, duration, 
    site_address, landmark, state, district, city, skills_required, description, posted_date, status, is_scam
)
VALUES
('Civil Construction Mason (Mistri)', 'Masonry / Rajmistri', 'L&T Metro Rail Project', '011-2334000', '011-2334000', '011-2334000', '011-2334000', 950, 950, 4, 4, '8 hours', '1-2 Months', 'Plot 42, Metro Yard, Phase 3', 'Near Okhla NSIC Metro Gate 2', 'Delhi', 'South Delhi', 'Okhla Phase 3', ARRAY['AAC Block Work', 'Brick Plastering', 'Line-Level Dori'], 'Brickwork, structural AAC block alignment, and beam plastering for elevated corridor station building. Safety helmet and boots provided at gate.', '2026-09-28', 'open', false),
('Commercial Interior Wall Painter', 'Painting & Finishing', 'Godrej Properties Luxury Towers', '040-2345000', '040-2345000', '040-2345000', '040-2345000', 850, 850, 3, 3, '8 hours', '2-4 Weeks', 'Tower B, Financial District', 'Beside Wipro Circle', 'Telangana', 'Hyderabad', 'Gachibowli', ARRAY['Putty Sanding', 'Roller Emulsion', 'Ceiling Primer'], 'Putty smoothing, primer coat, and double roller emulsion application on 2BHK interior ceilings and partition walls. Immediate daily payout.', '2026-09-28', 'open', false),
('Three-Phase Industrial Conduit Electrician', 'Electrical & Wiring', 'Tata BlueScope Industrial Sheds', '020-2740000', '020-2740000', '020-2740000', '020-2740000', 1000, 1000, 2, 2, '8 hours', '1-2 Weeks', 'Sector 10, MIDC Industrial Area', 'Opposite Century Enka', 'Maharashtra', 'Pune', 'Bhosari MIDC', ARRAY['3-Phase DB Termination', 'Cable Tray Laying', 'Conduit Bending'], 'Rigid PVC/GI cable tray laying, three-phase distribution box termination, and continuity testing for manufacturing warehouse. Certified Wireman preferred.', '2026-09-27', 'open', false),
('Sanitary Drainage & CPVC Pipeline Fitter', 'Plumbing & Sanitation', 'Prestige Tech Cloud Park', '080-2558000', '080-2558000', '080-2558000', '080-2558000', 900, 900, 3, 3, '8 hours', '2-3 Weeks', 'Tower 3, Electronic City Phase 1', 'Near Infosys Gate 4', 'Karnataka', 'Bengaluru Urban', 'Electronic City', ARRAY['CPVC Solvent Weld', 'Shaft Pipe Clamping', 'Pressure Testing'], 'Vertical shaft drainage stack jointing, underground sewer line slope alignment, and hydro-testing of pressure lines in commercial block.', '2026-09-28', 'open', false),
('Architectural Flush Door & Modular Carpenter', 'Carpentry & Woodwork', 'Adani Shantigram Township', '079-2656000', '079-2656000', '079-2656000', '079-2656000', 950, 950, 5, 5, '8 hours', '1-2 Months', 'Sector 5, SG Highway Bypass', 'Next to Belvedere Club', 'Gujarat', 'Ahmedabad', 'Vaishno Devi Circle', ARRAY['Door Frame Jam Alignment', 'Mortise Lock Fitting', 'Laminate Pasting'], 'Pre-hung door frame leveling, lock mortising, and modular laminate wardrobe carcass installation for luxury high-rise apartments.', '2026-09-27', 'open', false),
('HVAC Ducting & Heavy Plate MIG Welder', 'Welding & Fabrication', 'KEC International Heavy Fab Yard', '033-2287000', '033-2287000', '033-2287000', '033-2287000', 1050, 1050, 2, 2, '8 hours', '3-4 Weeks', 'Industrial Estate Gate 1', 'Near Brace Bridge Railway Station', 'West Bengal', 'Kolkata', 'Taratala Industrial Area', ARRAY['MIG/MAG CO2 Welding', 'Duct Seam Welding', 'Grinding & Beveling'], 'CO2 Shielded MIG welding of heavy structural box girders and ventilation ducts. Must pass horizontal fillet weld visual inspection.', '2026-09-26', 'open', false),
('Heavy-Duty Bar Bending & Mat Tier (Rebar)', 'Bar Bending / Steel Fixing', 'Dilip Buildcon Highway Interchange', '0141-2740000', '0141-2740000', '0141-2740000', '0141-2740000', 850, 850, 8, 8, '8 hours', '1-2 Months', 'NH-48 Interchange Pier 14', 'Near Mansarovar Ring Road Exit', 'Rajasthan', 'Jaipur', 'Mansarovar', ARRAY['25mm TMT Bending', 'Rebar Mat Binding', 'Cover Block Placement'], 'Cutting and manual lever-bending of 16mm/25mm Fe-550D TMT bars, tying reinforcement cage mats for highway bridge pier foundations.', '2026-09-28', 'open', false),
('Heavy Earthmoving Excavator / JCB Operator', 'Heavy Equipment Operation', 'Megha Engineering & Infra (MEIL)', '0866-2470000', '0866-2470000', '0866-2470000', '0866-2470000', 1200, 1200, 1, 1, '8 hours', '2-3 Months', 'Polavaram Canal Reach 4', 'Near Ibrahimpatnam Cross', 'Andhra Pradesh', 'Krishna', 'Vijayawada', ARRAY['Trench Sloping', 'Foundation Footing Digging', 'Hydraulic Safety Checks'], 'Operating 20-ton tracked excavator for canal embankment trenching and backfilling. Valid Heavy Commercial driving license mandatory.', '2026-09-27', 'open', false),
('High-Rise Cuplock Scaffolding & Catch-Net Rigger', 'Scaffolding & Rigging', 'Shapoorji Pallonji Engineering', '0124-4552000', '0124-4552000', '0124-4552000', '0124-4552000', 950, 950, 5, 5, '8 hours', '1 Month', 'Sector 29 Commercial Hub', 'Adjacent to IFFCO Chowk Metro', 'Haryana', 'Gurugram', 'Cyber City', ARRAY['Cuplock Standard Erection', 'Ledger Leveling', 'Safety Net Rigging'], 'Erecting external cantilevered cuplock staging, toe-boards, and safety catch nets up to 14th floor level. Full safety compliance required.', '2026-09-28', 'open', false),
('Underground Stormwater Drainage & Chamber Mason', 'Civil Masonry & Pipe Laying', 'Afcons Infrastructure Ltd', '044-26882000', '044-26882000', '044-26882000', '044-26882000', 900, 900, 6, 6, '8 hours', '3 Weeks', 'Industrial Road Sector 2', 'Near TI Cycles Factory', 'Tamil Nadu', 'Chennai', 'Ambattur', ARRAY['NP3 Pipe Alignment', 'Manhole Plastering', 'Cement Grout Sealing'], 'Aligning reinforced concrete NP3 pipes, joint grouting, and manhole brick chamber masonry. PPE and hydration provisions on site.', '2026-09-27', 'open', false),
('Structural Steel Shielded Metal Arc Welder (SMAW)', 'Structural Arc Welding', 'Bharat Heavy Electricals Project Site', '0542-2582000', '0542-2582000', '0542-2582000', '0542-2582000', 1100, 1100, 4, 4, '8 hours', '2 Months', 'Industrial Area Phase 2', 'Near Ramnagar Ganga Bridge', 'Uttar Pradesh', 'Varanasi', 'Ramnagar', ARRAY['6013/7018 Electrodes', 'Multi-Pass Bevel Weld', 'Overhead Position Arc'], 'Multi-pass fillet and groove welding of structural MS I-beams and gusset plates. Auto-darkening welding helmet provided.', '2026-09-26', 'open', false),
('National Highway Elevated Flyover Formwork Carpenter', 'Formwork Carpentry', 'National Highways Authority Contractors', '0612-2592000', '0612-2592000', '0612-2592000', '0612-2592000', 950, 950, 6, 6, '8 hours', '1-2 Months', 'Danapur Elevated Highway Pier 28', 'Beside Danapur Railway Station', 'Bihar', 'Patna', 'Danapur', ARRAY['Film-Faced Shuttering Ply', 'Acro Span Props', 'Formwork Releasing Agent'], 'Steel-faced plywood formwork erection, prop alignment, and releasing oil application for PSC box girders. Lunch break and fresh drinking water on site.', '2026-09-28', 'open', false)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- 7. SEED INITIAL WORKERS & CONTRACTORS DATA
-- ==============================================================================
INSERT INTO public.workers (name, phone, trade, role, company_name, business_category, gstin, wage, experience, status, state, district, city, verified, photo_skill_verified)
VALUES
('Sunil Sharma', '9848011223', 'Masonry / Rajmistri', 'worker', NULL, NULL, NULL, 950, 8, 'Available', 'Telangana', 'Hyderabad', 'Gachibowli', true, true),
('Pradeep Patil', '9822014455', 'Painting & Finishing', 'worker', NULL, NULL, NULL, 900, 6, 'Available', 'Maharashtra', 'Pune', 'Kothrud', true, true),
('Balasubramanian S.', '9840015566', 'Electrical & Wiring', 'worker', NULL, NULL, NULL, 950, 6, 'Available', 'Tamil Nadu', 'Chennai', 'Ambattur', true, true),
('Rajesh Patidar', '9879016677', 'Carpentry & Woodwork', 'worker', NULL, NULL, NULL, 900, 7, 'Available', 'Gujarat', 'Ahmedabad', 'Sanand', true, true),
('Dilip Mondal', '9831017788', 'Plumbing & Sanitation', 'worker', NULL, NULL, NULL, 850, 5, 'Available', 'West Bengal', 'Kolkata', 'Salt Lake', true, true),
('Apex Civil Infrastructure', '011-2334000', 'Civil Contracting Firm', 'employer', 'Apex Civil Infrastructure Ltd', 'General Contractor', '07AAAAA0000A1Z5', 0, 12, 'Active Employer', 'Delhi', 'South Delhi', 'Okhla Phase 3', true, true),
('Deccan Interiors & Buildcon', '040-2345000', 'Interior Finishing & Fitout', 'employer', 'Deccan Interiors & Buildcon LLP', 'Interior Contractor', '36BBBBB1111B1Z2', 0, 9, 'Active Employer', 'Telangana', 'Hyderabad', 'Gachibowli', true, true)
ON CONFLICT DO NOTHING;
